name: organisation_api
description: Dart package which manages the organisation domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  bloc: ^8.1.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  rxdart: ^0.27.7

dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: