name: server_api
description: Dart package which manages the server domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  bloc: ^8.1.2
  rxdart: ^0.27.7
  native_context_menu: ^0.2.2+5
  utils:
    path: ../utils
  organisation_api:
    path: ../organisation_api