name: accounting_api
description: Dart package which manages the accounting domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  bloc: ^8.1.2
  rxdart: ^0.27.7
  organisation_api:
    path: ../organisation_api
  user_api:
    path: ../user_api
  server_api:
    path: ../server_api
  utils:
    path: ../utils